[package]
name = "goto-rs"
version = "0.4.0"
authors = ["Sylvester Chin <sylvester.csw@gmail.com>"]
edition = "2024"
rust-version = "1.85"
description = "*gt* is a zsh-friendly directory jumper that learns where you go and gets you back there quickly."
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
repository = "https://github.com/slai11/goto"

[dependencies]
anyhow = "1.0.104"
clap = "4.6.7"
csv = "1.4.0"
dirs = "7.0.0"
inquire = "0.9.4"
termcolor = "1.4.1"
