name: ci
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    name: test
    env:
      # For some builds, we use cross to test on 32-bit and musl targets.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        # We test goto on its minimum supported Rust version, along with
        # stable for good measure.
        - pinned
        - stable
        - musl
        - arm
        - macos
        - win-msvc
        - win-gnu
        include:
        - build: pinned
          os: ubuntu-24.04
          rust: 1.85.0
        - build: stable
          os: ubuntu-24.04
          rust: stable
        - build: musl
          os: ubuntu-24.04
          rust: stable
          target: x86_64-unknown-linux-musl
        - build: arm
          os: ubuntu-24.04
          rust: stable
          target: arm-unknown-linux-gnueabihf
        - build: macos
          os: macos-15
          rust: 1.85.0
        - build: win-msvc
          os: windows-2025
          rust: stable
        - build: win-gnu
          os: windows-2025
          rust: stable-x86_64-gnu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Use Cross
      if: matrix.target != ''
      shell: bash
      run: |
        cargo install cross --locked
        echo "CARGO=cross" >> "$GITHUB_ENV"
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> "$GITHUB_ENV"

    - name: Build goto
      run: ${{ env.CARGO }} build --verbose --locked ${{ env.TARGET_FLAGS }}

    - name: Run tests
      run: ${{ env.CARGO }} test --verbose --locked ${{ env.TARGET_FLAGS }}

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy
    - name: Check clippy linting
      run: cargo clippy --locked --all-targets --all-features -- -D warnings

  cargo-publish-dryrun:
    name: cargo publish (dry run)
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Publish to crates.io
      run: cargo publish --locked --dry-run
